### PR TITLE
Improve Code Quality

### PR DESCRIPTION
**Pull request by pateljay15**
Improved Code Quality by removing Design code smells and Implementation code smells. Code is working fine after Refactoring and all Tests Cases are passed. Moreover, I have added 5 additional Unit Test Cases for MachineId Class.

### CODE REVIEW

**Comment by pateljay15** [comment]
After reviewing the pull request, you think the changes I have made are acceptable to be merged into this Open Source Repository. Then it will be helpful for me if you accept the pull request before 31st 11:59 PM.

**Comment by fabiolimace** [comment]
Hi, @pateljay15 

Your work really improved readability and removed some of the project's smells. Thank you very much. However, I had already approved the changes when this build problem occurred. I think that the code will be ready for merge after this.

```
﻿2024-03-31T12:59:40.1910969Z ##[group]Run mvn -B -q -ff -ntp package --file pom.xml
mvn -B -q -ff -ntp package --file pom.xml
shell: /usr/bin/bash -e {0}
env:
  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.402-6/x64
  JAVA_HOME_8_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.402-6/x64
 [ERROR] Some problems were encountered while processing the POMs:
[FATAL] 'dependencies.dependency[com.github.f4b6a3:uuid-creator:5.3.8-SNAPSHOT]' for com.github.f4b6a3:uuid-creator:5.3.8-SNAPSHOT is referencing itself. @ line 41, column 15
 @ 
 The build could not read 1 project -> [Help 1]
   
   The project com.github.f4b6a3:uuid-creator:5.3.8-SNAPSHOT (/home/runner/work/uuid-creator/uuid-creator/pom.xml) has 1 error
     'dependencies.dependency[com.github.f4b6a3:uuid-creator:5.3.8-SNAPSHOT]' for com.github.f4b6a3:uuid-creator:5.3.8-SNAPSHOT is referencing itself. @ line 41, column 15
 
 To see the full stack trace of the errors, re-run Maven with the -e switch.
 Re-run Maven using the -X switch to enable full debug logging.
 
 For more information about the errors and possible solutions, please read the following articles:
 [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
Process completed with exit code 1.
```

**Comment by pateljay15** [comment]
hey @fabiolimace, thanks for your time for letting me know the issue. Solved that problem, see if its possible for you to review and accept the pull request.

**Comment by fabiolimace** [comment]
Great job! Thanks @pateljay15 !

**Comment by pateljay15** [comment]
Thanks a lot !! @fabiolimace  for accepting my pull request.

**Pull request merged**
